services:

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  task-db:
    image: postgres:16
    container_name: task-db
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - task-db-data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - user-db

  task-service:
    build:
      context: ./task-service
    container_name: task-service
    ports:
      - "8080:8080"
    depends_on:
      - task-db
      - user-service

volumes:
  user-db-data:
  task-db-data: