apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: team-task-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: team-task-hub-task-service:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 8080
