apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: team-task-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: team-task-hub-user-service:latest
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 8081

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
