apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: user-db
  namespace: team-task-hub

spec:
  serviceName: user-db
  replicas: 1

  selector:
    matchLabels:
      app: user-db

  template:
    metadata:
      labels:
        app: user-db

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: user_db

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pvc
